CREATE TABLE [dbo].[TMS_Area]
(
[Area_ID] [int] NOT NULL IDENTITY(1, 1),
[Area_Desc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMS_Area] ADD CONSTRAINT [PK_TMS_Area] PRIMARY KEY CLUSTERED  ([Area_ID]) ON [PRIMARY]
GO
