CREATE TABLE [dbo].[TMS_User_Priv]
(
[Priv_ID] [int] NOT NULL IDENTITY(1, 1),
[Priv_Desc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMS_User_Priv] ADD CONSTRAINT [PK_TMS_User_Priv] PRIMARY KEY CLUSTERED  ([Priv_ID]) ON [PRIMARY]
GO
